name: 'Build and test icepack'
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/firedrakeproject/firedrake-vanilla:2023-10
      options: --user root
    steps:
      - name: Install patchelf
        run: |
          apt update
          apt install -yq patchelf
      - name: Check out git repository
        uses: actions/checkout@v3
      - name: Activate Firedrake virtual environment
        run: |
          . /home/firedrake/firedrake/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Install package
        run: |
          pip install git+https://github.com/icepack/Trilinos.git@190384db6cb1d148cea36f2d8d69033a90b2d991
          pip install git+https://github.com/icepack/pyrol.git@3bc1802e436eda8949a286abf54528c7a882f706
          pip install --editable .
      - name: Run tests
        run: pytest
